[package]
name = "serve"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13.0"

[dev-dependencies]
anyhow = "1.0.40"
assert_cmd = "0.10"
predicates = "1"
url = "2.2.2"
